// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xoolxvmcwclzknzfvchz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhvb2x4dm1jd2NsemtuemZ2Y2h6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcxMjM0NDYsImV4cCI6MjA5MjY5OTQ0Nn0.XCDYIfm4lq5dlNq-l1Sumd9eD64K85PsaKsdifdnw34";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});